#image:
#  file: .gitpod.Dockerfile
tasks:
  - init: >
      echo true
vscode:
  extensions:
    - HalcyonTechLtd.code-for-ibmi
    - barrettotte.ibmi-languages
    - HalcyonTechLtd.vscode-ibmi-walkthroughs
    - BrianJGarland.vscode-rpgfree
